#!/bin/bash

#################################################
# Script:	esperanza			#
# Author: 	Leonardo Costa			#
# Contact:	lccoder.php@gmail.com		#
# Created:	2015-12-29 01:35:37 AM		#
# Verion:	1.0				#
#################################################

type ffmpeg 2>/dev/null ; test $? -eq 1 && su root -c "dnf install ffmpeg -y"


if [ ! $1 ] && [ ! $2 ]
then
	echo -e "Digite o nome dos dois arquivos, o original e o nome do arquivo de saida sem extensao \n"
	exit 0
	
else

	/usr/bin/ffmpeg -i $1 -strict -2 -vcodec libx264 $2.mp4 2>/dev/null
	
	if [ $? -eq 0 ]
	then
		echo -e "O arquivo $2.mp4 foi gerado com sucesso!\n"
		exit 0
	else
		echo -e "Houve um erro ao gerar o  arquivo $2.mp4!\n"
                exit 0
	fi

fi
	

